In [108]:
# Primero voy a importar algunas Bibliotecas:
import pynwb
from datetime import datetime
from dateutil import tz
import numpy as np

# Then I can import the NWB file:
nwb = pynwb.NWBHDF5IO("sub-2023-01-09-15-SWF702_ses-20230109_behavior+image+ophys.nwb", "r").read()

print(nwb)

root pynwb.file.NWBFile at 0x2394741984896
Fields:
  acquisition: {
    CalciumImageSeries <class 'abc.MultiChannelVolumeSeries'>,
    NeuroPALImageRaw <class 'abc.MultiChannelVolume'>
  }
  devices: {
    NIR Config <class 'pynwb.device.Device'>,
    Spinning Disk Confocal <class 'pynwb.device.Device'>
  }
  file_create_date: [datetime.datetime(2024, 6, 12, 15, 41, 43, 509730, tzinfo=tzoffset(None, -25200))]
  identifier: 2023-01-09-15
  imaging_planes: {
    CalciumImVol <class 'abc.ImagingVolume'>,
    NeuroPALImVol <class 'abc.ImagingVolume'>
  }
  institution: MIT
  intervals: {
    heat_stimulus <class 'pynwb.epoch.TimeIntervals'>
  }
  lab: Flavell Laboratory
  processing: {
    BF_NIR <class 'pynwb.base.ProcessingModule'>,
    Behavior <class 'pynwb.base.ProcessingModule'>,
    CalciumActivity <class 'pynwb.base.ProcessingModule'>,
    NeuroPAL <class 'pynwb.base.ProcessingModule'>
  }
  related_publications: ['https://doi.org/10.1016/j.cell.2023.07.035']
  session_description:

In [109]:
nwb.session_description # (str) Ventral cord at the bottom when head faces left; no mature eggs
#Heat stim at t~801
#High pumping variance pre-stim, almost no pumping post-stim
#Post-stim reversals are not super frequent but long lasting
#21 is a backup of 16

nwb.identifier # (str) 2023-01-09-15
nwb.session_start_time # (datetime) 2023-01-09T00:00:00-08:00
nwb.file_create_date # (datetime) 2024-06-12T15:41:43.509730-07:00
nwb.timestamps_reference_time # (datetime) 2023-01-09T00:00:00-08:00
nwb.experimenter # (List[str]) []
nwb.experiment_description # (str)
nwb.institution # (str) MIT
nwb.keywords # (List[str]) []
nwb.protocol # (str)
nwb.lab # (str) Flavell Laboratory
nwb.subject # (Subject)
nwb.subject.age # (str)
nwb.subject.age__reference # (str)
nwb.subject.description # (str) Ventral cord at the bottom when head faces left; no mature eggs
#Heat stim at t~801
#High pumping variance pre-stim, almost no pumping post-stim
#Post-stim reversals are not super frequent but long lasting
#21 is a backup of 16

nwb.subject.genotype # (str)
nwb.subject.sex # (str) O
nwb.subject.species # (str) http://purl.obolibrary.org/obo/NCBITaxon_6239
nwb.subject.subject_id # (str) 2023-01-09-15-SWF702
nwb.subject.weight # (str)
nwb.subject.date_of_birth # (datetime) 2023-01-09T00:00:00-08:00

CalciumImageSeries = nwb.acquisition["CalciumImageSeries"] # (MultiChannelVolumeSeries) GCaMP6s series images. Dimensions should be (t, x, y, z, C).
CalciumImageSeries.starting_time # 0 sec
CalciumImageSeries.rate # 1.7 Hz

NeuroPALImageRaw = nwb.acquisition["NeuroPALImageRaw"] # (MultiChannelVolume)

heat_stimulus = nwb.intervals["heat_stimulus"] # (TimeIntervals) Heat stimulation driven by 1436-nm 500-mW laser. Mean temperature set to be 10.0C over first second of stimulation with a 0.39 sec exponential decay, returning to baseline within 3 sec. Start and stop time are in seconds.
heat_stimulus["id"] # (h5py.Dataset) shape [1]; dtype <i8 undefined
heat_stimulus["start_time"] # (h5py.Dataset) shape [1]; dtype <f8 Start time of epoch, in seconds
heat_stimulus["stimulus"] # (h5py.Dataset) shape [1]; dtype |O which stimulus is active
heat_stimulus["stop_time"] # (h5py.Dataset) shape [1]; dtype <f8 Stop time of epoch, in seconds

BF_NIR = nwb.processing["BF_NIR"] # (ProcessingModule) The light path used to image behavior was in a reflected brightfield (NIR) configuration. Light supplied by an 850-nm LED (M850L3, Thorlabs) was collimated and passed through an 850/10 bandpass filter (FBH850-10, Thorlabs). Illumination light was reflected towards the sample by a half mirror and was focused on the sample through a 10x objective (CFI Plan Fluor 10x, Nikon). The image from the sample passed through the half mirror and was filtered by another 850-nm bandpass filter of the same model. The image was captured by a CMOS camera (BFS-U3-28S5M-C, FLIR).

BrightFieldNIR = nwb.processing["BF_NIR"]["BrightFieldNIR"] # (ImageSeries) The light path used to image behavior was in a reflected brightfield (NIR) configuration. Light supplied by an 850-nm LED (M850L3, Thorlabs) was collimated and passed through an 850/10 bandpass filter (FBH850-10, Thorlabs). Illumination light was reflected towards the sample by a half mirror and was focused on the sample through a 10x objective (CFI Plan Fluor 10x, Nikon). The image from the sample passed through the half mirror and was filtered by another 850-nm bandpass filter of the same model. The image was captured by a CMOS camera (BFS-U3-28S5M-C, FLIR).
BrightFieldNIR.timestamps # (h5py.Dataset) shape [19377]; dtype <f8

Behavior = nwb.processing["Behavior"] # (ProcessingModule) Behavioral data

angular_velocity = nwb.processing["Behavior"]["angular_velocity"] # (BehavioralTimeSeries)

body_curvature = nwb.processing["Behavior"]["body_curvature"] # (BehavioralTimeSeries)

dorsalness = nwb.processing["Behavior"]["dorsalness"] # (BehavioralTimeSeries)

feedingness = nwb.processing["Behavior"]["feedingness"] # (BehavioralTimeSeries)

forwardness = nwb.processing["Behavior"]["forwardness"] # (BehavioralTimeSeries)

head_curvature = nwb.processing["Behavior"]["head_curvature"] # (BehavioralTimeSeries)

pumping = nwb.processing["Behavior"]["pumping"] # (BehavioralTimeSeries)

reversal_events = nwb.processing["Behavior"]["reversal_events"] # (BehavioralEvents)

velocity = nwb.processing["Behavior"]["velocity"] # (BehavioralTimeSeries)

CalciumActivity = nwb.processing["CalciumActivity"] # (ProcessingModule) Calcium time series metadata, segmentation, and fluorescence data

CalciumSeriesSegmentation = nwb.processing["CalciumActivity"]["CalciumSeriesSegmentation"] # (ImageSegmentation)

Aligned_neuron_coordinates = nwb.processing["CalciumActivity"]["CalciumSeriesSegmentation"]["Aligned_neuron_coordinates"] # (PlaneSegmentation) Neuron center coordinates in aligned space

NeuronIDs = nwb.processing["CalciumActivity"]["NeuronIDs"] # (SegmentationLabels)

SignalRawFluor = nwb.processing["CalciumActivity"]["SignalRawFluor"] # (Fluorescence)

SignalCalciumImResponseSeries = nwb.processing["CalciumActivity"]["SignalRawFluor"]["SignalCalciumImResponseSeries"] # (RoiResponseSeries) Raw calcium fluorescence activity
SignalCalciumImResponseSeries.data # (h5py.Dataset) shape [1615, 147]; dtype <f8
SignalCalciumImResponseSeries.timestamps # (h5py.Dataset) shape [1615]; dtype <f8

NeuroPAL = nwb.processing["NeuroPAL"] # (ProcessingModule) NeuroPAL image metadata and segmentation

NeuroPALSegmentation = nwb.processing["NeuroPAL"]["NeuroPALSegmentation"] # (ImageSegmentation)

NeuroPALNeurons = nwb.processing["NeuroPAL"]["NeuroPALSegmentation"]["NeuroPALNeurons"] # (PlaneSegmentation) Centers of NeuroPAL volume.

NeuronSegmentationROIs = nwb.processing["NeuroPAL"]["NeuroPALSegmentation"]["NeuronSegmentationROIs"] # (PlaneSegmentation) Segmentation of NeuroPAL volume. IDs found in NeuroPALNeurons.
NeuronSegmentationROIs["image_mask"].data # (h5py.Dataset) shape [1, 264, 97, 57] [ num_masks, num_rows, num_columns ]; dtype <u2

<HDF5 dataset "image_mask": shape (1, 264, 97, 57), type "<u2">

In [110]:
#Ok primero entendamos que hay adentro de esta carpeta:
print(CalciumActivity)

CalciumActivity pynwb.base.ProcessingModule at 0x2394681446752
Fields:
  data_interfaces: {
    CalciumSeriesSegmentation <class 'pynwb.ophys.ImageSegmentation'>,
    NeuronIDs <class 'abc.SegmentationLabels'>,
    SignalCalciumImResponseSeries <class 'pynwb.ophys.RoiResponseSeries'>,
    SignalRawFluor <class 'pynwb.ophys.Fluorescence'>
  }
  description: Calcium time series metadata, segmentation, and fluorescence data



In [111]:
# Luego observamos que hay adentro del signal Calcium Im Response Series:
print(CalciumActivity["SignalCalciumImResponseSeries"])

SignalCalciumImResponseSeries pynwb.ophys.RoiResponseSeries at 0x2394683185856
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (1615, 147), type "<f8">
  description: Raw calcium fluorescence activity
  interval: 1
  offset: 0.0
  resolution: -1.0
  rois: rois <class 'hdmf.common.table.DynamicTableRegion'>
  timestamps: <HDF5 dataset "timestamps": shape (1615,), type "<f8">
  timestamps_unit: seconds
  unit: lumens



In [112]:
CalciumActivityData = CalciumActivity["SignalCalciumImResponseSeries"].data[:]
print(CalciumActivityData)

[[0.97548135 0.13819319 0.55957216 ... 0.23433923 0.47069949 0.18628069]
 [0.9697448  0.15736432 0.5148136  ... 0.23427811 0.44964368 0.20945986]
 [0.92447707 0.19908959 0.4692071  ... 0.21915565 0.47079901 0.20281884]
 ...
 [0.36895703 0.31864749 0.40226195 ... 0.37455477 0.97232266 0.29607663]
 [0.36910376 0.31877422 0.40242193 ... 0.37470373 0.97270935 0.29619438]
 [0.36925055 0.31890099 0.40258197 ... 0.37485275 0.97309619 0.29631217]]


In [113]:
CalciumActivityDataTimestamps = CalciumActivity["SignalCalciumImResponseSeries"].timestamps[:]
print(CalciumActivityDataTimestamps)

[596998.99183538 596999.605491   597000.20550971 ... 597968.75410301
 597969.33593947 597969.92459442]


In [114]:
print(CalciumActivity["NeuronIDs"].labels[:])

['' '' 'ASEL' 'AIBL' 'AINL' 'AIZR' 'NSML' 'AWBL' 'AVJR' 'RMDVL' 'URBR'
 'CEPVR' 'RIBR' 'OLLR' 'AWCL' '' 'SAAVL' 'ADEL' '' 'RMDVR' '' 'URYVR'
 'IL1L' '' 'ADAL' 'AWAR' 'OLLL' 'OLQVR' 'M1' 'RIVR' 'URYVL' 'IL2DR'
 'URYDR' 'ASGR' 'ASER' 'I1R' 'FLPR' 'CEPDR' '' '' 'VB02' 'AWBR' '' 'AQR'
 'AVER' '' 'IL2VR' 'RICL' '' '' 'CEPDL' 'RMDDL' '' 'RMER' 'AINR' '' 'AVAR'
 'RIBL' '' '' 'OLQDR' 'AVDL' '' 'ASIL' 'AWCR' 'AUAR' '' 'I3' 'CEPVL'
 'SMDVL' 'AUAL' '' 'ASIR' '' '' '' 'I1L' 'M3L' 'M3R' 'AIBR' '' 'AVK?'
 'OLQVL' '' 'MCL' 'RIVL' 'IL2DL' 'OLQDL' 'URBL' 'SAAVR' 'I2L' '' 'AVAL'
 'IL1R' '' 'AVDR' 'ASGL' '' '' 'M2L' '' 'SMDVR' 'NSMR' 'ADLL' '' 'RMEL'
 'AVHL' 'RID' '' 'RIH' 'RIML' 'AIA?' 'RMDDR' 'URXL' 'ADER' '' 'M5' '' ''
 '' 'AIM?' 'URYDL' '' 'RIAL' '' 'RIMR' '' '' 'URADR' 'AVL' 'RICR' '' 'MI'
 'ADLR' '' '' 'IL1DL' 'URXR' '' '' 'M4' 'RMEV' '' 'IL1DR' 'FLPL' 'SMBVR'
 'I2R']


In [146]:
print(CalciumActivity["CalciumSeriesSegmentation"]["Aligned_neuron_coordinates"])

Aligned_neuron_coordinates pynwb.ophys.PlaneSegmentation at 0x2394666469312
Fields:
  colnames: ['voxel_mask' 'ID_labels']
  columns: (
    voxel_mask_index <class 'hdmf.common.table.VectorIndex'>,
    voxel_mask <class 'hdmf.common.table.VectorData'>,
    ID_labels <class 'hdmf.common.table.VectorData'>
  )
  description: Neuron center coordinates in aligned space
  id: id <class 'hdmf.common.table.ElementIdentifiers'>
  imaging_plane: CalciumImVol abc.ImagingVolume at 0x2394681845552
Fields:
  conversion: 1.0
  description: Imaging volume used to acquire calcium imaging data
  device: Spinning Disk Confocal pynwb.device.Device at 0x2394681845600
Fields:
  description: The light path used to image GCaMP, mNeptune, and the fluorophores in NeuroPAL at single cell resolution is an Andor spinning disk confocal system with Nikon ECLIPSE Ti microscope. Light supplied from a 150 mW 488 nm laser, 50 mW 560 nm laser, 100 mW 405 nm laser, or 140 mW 637 nm laser passes through a 5000 rpm Yokogaw

In [115]:
print(Behavior)

Behavior pynwb.base.ProcessingModule at 0x2394681446464
Fields:
  data_interfaces: {
    angular_velocity <class 'pynwb.behavior.BehavioralTimeSeries'>,
    body_curvature <class 'pynwb.behavior.BehavioralTimeSeries'>,
    dorsalness <class 'pynwb.behavior.BehavioralTimeSeries'>,
    feedingness <class 'pynwb.behavior.BehavioralTimeSeries'>,
    forwardness <class 'pynwb.behavior.BehavioralTimeSeries'>,
    head_curvature <class 'pynwb.behavior.BehavioralTimeSeries'>,
    pumping <class 'pynwb.behavior.BehavioralTimeSeries'>,
    reversal_events <class 'pynwb.behavior.BehavioralEvents'>,
    velocity <class 'pynwb.behavior.BehavioralTimeSeries'>
  }
  description: Behavioral data



In [156]:
print(Behavior["velocity"]["velocity"].timestamps[:])

[596998.99183538 596999.605491   597000.20550971 ... 597968.75410301
 597969.33593947 597969.92459442]


In [157]:
print(Behavior["velocity"]["velocity"].data[:])

[-0.12097129 -0.16902555 -0.05386446 ...  0.01109838  0.01413344
  0.00854741]
